### ISSUE TITLE
Mint Test POLS on Avalanche Testnet

### ISSUE THREAD

**Issue by tiagom87** [polkastarter/PolkastarterToken#1]
We need to have test POLS on the Avalanche test net as well. Feel free to send some to the following wallet before this issue is closed:

0x427D0A2c65eB5d146ED3b9e913A2eB0eac334B64

Thank you @SvenMeyer

**Comment by SvenMeyer** [comment]
Avalanche TEST FUJI C-Chain - Chain ID 43113

Testnet RPC URL : https://api.avax-test.network/ext/bc/C/rpc

Transaction : send 1000000 POLS

https://testnet.snowtrace.io/tx/0x50e8afb634ab8808b944f0215178bfa82e95b8f19f19218aeafab867aa233d93
